Repository msaimraz/Hacktoberfest_2023, pull requests merged in 2023-10, with the labels that each got.

#5 Added Delete a node in Linked List
  Delete_given_node_in_Linked_List.java
Labels: hacktoberfest-accepted 2023

#7 Create ReverseWordInString.java
  ReverseWordInString.java
Labels: hacktoberfest-accepted 2023

#8 Added Merge Two Sorted Linked List
  Merge_Two_Sorted_Linked_List.java
Labels: hacktoberfest-accepted 2023

#9 Reverse Linked List
  Reverse_Linked_List.java
Labels: hacktoberfest-accepted 2023

#11 Create Delete given node in a Linked List.java
  Delete given node in a Linked List.java
Labels: hacktoberfest-accepted 2023

#12 Added code to reverse a linked list using iterative approach in C++
  Reverse_Linkedlist_Iterative.cpp
Labels: hacktoberfest-accepted 2023

#13 Added code to reverse linked list using Recursive Approach in C++
  Reverse_LinkedList_Recursive.cpp
Labels: hacktoberfest-accepted 2023

#14 Sorting and Searching algorithms
  Searching/binarySearch.cpp
  Searching/linearSearch.cpp
  Sorting/bubblesort.cpp
  Sorting/insertionsort.cpp
  Sorting/selectionsort.cpp
Labels: hacktoberfest-accepted 2023

#15 Add mergesort.cpp in Sorting Folder
  Sorting/mergesort.cpp
Labels: hacktoberfest-accepted 2023

#16 Created a Separate folder for Java DSA Leetcode Code
  Java/Search/JumpSearch.java
  Java/Sort/BubbleSort.java
Labels: hacktoberfest-accepted 2023

#18 Create BFS.java
  BFS.java
Labels: hacktoberfest-accepted 2023

#17 Create GuessTheNumber.java
  GuessTheNumber.java
Labels: hacktoberfest-accepted 2023

#20 Added threding example using Python
  threding.py
Labels: hacktoberfest-accepted 2023

#19 Create Kadane.java
  Kadane.java
Labels: hacktoberfest-accepted 2023

#21 added Famous java BackTracing Problem - Verbal Arithmetic Puzzle
  Java/BackTracking/Verbal_Arithmetic_Puzzle.java
Labels: hacktoberfest-accepted 2023

#24 add data structures in c++
  C++/array.cpp
  C++/linked-list.cpp
  C++/queue.cpp
  C++/stack.cpp
Labels: hacktoberfest-accepted 2023

#25 reverse linked list in C++ code added to the file
  Reverse_linked_list.cpp
Labels: hacktoberfest-accepted 2023, hacktoberfest

#26 Create QuickSort
  Java/Sort/QuickSort
Labels: hacktoberfest

#27 Maths
  Java/Maths/isPowerOf2.java
Labels: hacktoberfest

#28 Create UniqueElementsFinder.java
  UniqueElementsFinder.java
Labels: hacktoberfest

#29 Create kmalhotra08 basketballgame
  kmalhotra08 basketballgame
Labels: hacktoberfest

#30 Added solution to Codeforces Pinely contest problem
  1863A - Channel.cpp
Labels: hacktoberfest

#31 Added code for Reverse of Linked List in C
  ReverseOfLinkedList.c.txt
Labels: hacktoberfest

#32 added knapsack code using dynamic programming
  C++/knapsack.cpp
Labels: hacktoberfest

#33 added code to delete given node in a sll
  deletion in sll.txt
Labels: hacktoberfest

#34 Create ImplementStrStr.java
  ImplementStrStr.java
Labels: hacktoberfest
